<?php
/**
 * Created by PhpStorm.
 * User: liulin
 * Date: 2017/3/7
 * Time: 上午8:47
 */
namespace app\controllers;
use app\models\News;
use yii\filters\auth\QueryParamAuth;
use yii\rest\ActiveController;
use yii\web\Response;

class InfoController extends ActiveController
{
    public $modelClass = 'app\M\News';
    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->user->enableSession = false;
    }
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['authenticator'] = [
            'class' => QueryParamAuth::className(),
        ];
        $behaviors['contentNegotiator']['formats']['text/html'] = Response::FORMAT_JSON;
        return $behaviors;
    }
}