<?php
/**
 * Created by PhpStorm.
 * User: liulin
 * Date: 2017/9/3
 * Time: 下午9:38
 */
namespace app\controllers;

use app\models\ModelFactory;
use Qiniu\QiniuUtil;
use Qiniu\Storage\UploadManager;
use Yii;
use yii\web\UploadedFile;
use app\models\Uploader;

class UploadController extends ComBaseController{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->enableCsrfValidation = false;
    }

    // 图片上传回调
    function actionImgcallback()
    {
        // 七牛Post我们这个地址了
        if(Yii::$app->request->isPost)
        {
            $model=ModelFactory::loadModel("videos_img");//取出图片表model
            $vi=$model::find()->where(["img_name"=>Yii::$app->request->post("key")])->one();
            if($vi)
            {
                $vi->isuploaded=1;
                $vi->save();

                $result=new \stdClass();
                $result->response="success";
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;  //设置当前 content-type为application/json
                return  $result;
            }

        }

    }

    function actionPicture() {
        $model = new Uploader();
        $request = Yii::$app->request;
        if ($request->isPost) {
            $model->imageFile = UploadedFile::getInstance($model, 'imageFile');
            $getUploadResult = $model->upload();
            return $getUploadResult;
        }
        return "";
    }

    function actionBase64() {
        $util = new QiniuUtil();
        $uploadMgr = new UploadManager();
        $token = $util->token;
        $domian = $util->domian;
        $request = Yii::$app->request;
        if ($request->isPost) {
            $base64 = $request->post('base64');
            if(preg_match('/^(data:\s*image\/(\w+);base64,)/', $base64, $result)) {
                $imgName = date('Ymdhis').'.'.$result[2];
                $image_url = $domian.$imgName;
                list($ret, $err) = $uploadMgr->putFile($token, $imgName, $base64);
                if ($err !== null) {
                    $result = [
                        'ret' => 0,
                        'data' => null,
                        'msg' => $err
                    ];
                } else {
                    $result = [
                        'data' => [
                            'url' => $image_url
                        ],
                        'ret' => 1
                    ];
                }
                return json_encode($result);
            }
        }
        return "";
    }

    //返回uptoken
    function actionUploadtoken() {
        $userid = 0; //默认是0，代表超级管理员
        $util = new QiniuUtil();
        $ret = $util->getUploadToken($userid);
        return json_encode($ret);
    }
}